export const randomTitles = [
    "Analyzing Blockchain Integration in Supply Chain Management",
    "Exploring AI-driven Solutions for Renewable Energy Optimization",
    "Enhancing Cybersecurity Measures through Machine Learning Algorithms",
    "Investigating the Impact of Social Media on Consumer Behavior",
    "Developing a Virtual Reality Training Platform for Healthcare Professionals",
    "Optimizing Urban Transportation Systems using Big Data Analytics",
    "Assessing the Effectiveness of Telemedicine in Rural Healthcare",
    "Designing a Smart Home System for Elderly Care",
    "Implementing IoT Solutions for Sustainable Agriculture Practices",
    "Examining the Role of Artificial Intelligence in Personalized Education",
    "Improving E-commerce Recommendations with Deep Learning Models",
    "Exploring the Potential of Quantum Computing in Financial Analysis",
    "Addressing Mental Health Challenges with AI-driven Chatbots",
    "Analyzing Sentiment Trends in Social Media for Market Forecasting",
    "Designing a Smart Grid System for Efficient Energy Distribution",
    "Developing a Blockchain-based Voting System for Secure Elections",
    "Assessing the Impact of Autonomous Vehicles on Urban Planning",
    "Investigating the Feasibility of 3D Printing in Construction",
    "Enhancing Disaster Response with Drone Technology",
    "Designing a Health Monitoring System for Wearable Devices",
    "Optimizing Energy Consumption in Smart Buildings",
    "Exploring Bioinformatics Approaches for Personalized Medicine",
    "Analyzing Financial Market Volatility with Machine Learning",
    "Implementing Robotics in Industrial Automation Processes",
    "Developing AI-powered Language Translation Systems",
    "Investigating the Role of IoT in Environmental Monitoring",
    "Exploring Ethical Considerations in AI Development",
    "Designing a Virtual Reality Simulation for Emergency Response Training",
    "Enhancing Data Privacy in Cloud Computing Environments",
    "Assessing the Potential of Augmented Reality in Education",
    "Analyzing Cybersecurity Risks in Healthcare Systems",
    "Developing AI-driven Personalized Learning Platforms",
    "Designing Autonomous Drones for Wildlife Conservation",
    "Exploring the Role of Blockchain in Supply Chain Transparency",
    "Optimizing Logistics Operations with Predictive Analytics",
    "Enhancing Customer Experience through Voice Recognition Technology",
    "Assessing the Impact of AI on Job Automation and Employment",
    "Investigating the Role of Robotics in Elderly Care Facilities",
    "Analyzing Social Media Influence on Political Discourse",
    "Designing Smart Traffic Management Systems for Urban Areas",
    "Exploring Quantum Computing Applications in Cryptography",
    "Developing AI-driven Personal Financial Management Tools",
    "Enhancing Cybersecurity with Biometric Authentication Systems",
    "Assessing the Feasibility of 5G Networks in Rural Areas",
    "Analyzing the Role of AI in Predictive Healthcare",
    "Exploring the Use of Blockchain in Intellectual Property Rights",
    "Designing AI-powered Virtual Assistants for Customer Service",
    "Optimizing Energy Efficiency in Data Centers",
    "Assessing the Impact of IoT on Smart Cities Development",
    "Investigating the Feasibility of Hydroponic Farming in Urban Environments",
    "Analyzing Social Media Algorithms and Their Impact on Society",
    "Developing AI-driven Predictive Maintenance Systems for Industry",
    "Exploring the Role of AI in Climate Change Mitigation",
    "Designing Autonomous Vehicles for Last-Mile Delivery Services",
    "Optimizing Healthcare Resource Allocation with Data Analytics",
    "Assessing the Impact of IoT on Supply Chain Management",
    "Investigating the Potential of AI in Drug Discovery",
    "Analyzing the Influence of AI in Art and Creativity",
    "Developing AI-driven Fraud Detection Systems for Financial Institutions",
    "Exploring the Use of Blockchain in Digital Identity Management",
    "Designing Smart Grids for Sustainable Energy Distribution",
    "Optimizing Inventory Management with RFID Technology",
    "Assessing the Impact of AI on Human Resource Management",
    "Investigating the Feasibility of 3D Bioprinting in Medicine",
    "Analyzing the Role of AI in Predictive Maintenance for Manufacturing",
    "Exploring the Use of Blockchain in Food Supply Chain Traceability",
    "Designing AI-driven Personalized Shopping Experiences",
    "Optimizing Fleet Management with IoT and Big Data",
    "Assessing the Feasibility of AI in Remote Patient Monitoring",
    "Investigating the Potential of Blockchain in Healthcare Data Management",
    "Analyzing the Influence of AI in Financial Trading",
    "Developing AI-driven Chatbots for Mental Health Support",
    "Exploring the Role of IoT in Smart Agriculture",
    "Designing Autonomous Surveillance Systems for Security",
    "Optimizing Energy Consumption with Smart Home Technologies",
    "Assessing the Impact of AI in Drug Repurposing",
    "Investigating the Feasibility of Blockchain in Real Estate Transactions",
    "Analyzing the Role of AI in Personalized Marketing",
    "Exploring the Use of Blockchain in Digital Voting Systems",
    "Designing AI-driven Personalized Fitness Programs",
    "Optimizing Waste Management with IoT Solutions",
    "Assessing the Feasibility of AI in Predictive Policing",
    "Investigating the Potential of Blockchain in Intellectual Property Protection",
    "Analyzing the Influence of AI in Content Creation",
    "Developing AI-driven Virtual Try-on Systems for Fashion",
    "Exploring the Role of IoT in Smart Energy Grids",
    "Designing Autonomous Inventory Management Systems",
    "Optimizing Crop Yield Prediction with Machine Learning",
    "Assessing the Impact of AI in Precision Agriculture",
    "Investigating the Feasibility of Blockchain in Healthcare Records Management",
    "Analyzing the Role of AI in Urban Planning",
    "Exploring the Use of Blockchain in Humanitarian Aid Distribution",
    "Designing AI-driven Personalized News Aggregation Platforms",
    "Optimizing Supply Chain Efficiency with IoT and Blockchain",
    "Assessing the Feasibility of AI in Wildlife Conservation",
    "Investigating the Potential of Blockchain in Online Voting Systems",
    "Analyzing the Influence of AI in Music Composition",
    "Developing AI-driven Speech Recognition Systems for Accessibility",
    "Exploring the Role of IoT in Smart Water Management",
    "Designing Autonomous Security Systems for Smart Homes",
]